version: '3.9'

services:
  testsvr:
    container_name: testsvr
    build:
      context: ../
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    
    environment:
      - TESTCONTAINERS_HOST_OVERRIDE=host.docker.internal
    

